#!/bin/sh
python general_detection1.py mask2.jpg cascade.xml haarcascades/haarcascade_frontalface_default.xml haarcascades/haarcascade_frontalface_alt.xml haarcascades/haarcascade_frontalface_alt2.xml haarcascades/haarcascade_frontalface_alt_tree.xml haarcascades/haarcascade_profileface.xml
